Traceback (most recent call last):
  File "/rds/general/user/dx21/home/IRP_flash_calculation_accelaration/XGB_experience/XGB.py", line 174, in <module>
    run_bayes_optimize(55, i)
  File "/rds/general/user/dx21/home/IRP_flash_calculation_accelaration/XGB_experience/XGB.py", line 134, in run_bayes_optimize
    X_train, y_train, X_test, y_test, Material_ID = relate_data[data_index]
  File "/rds/general/user/dx21/home/IRP_flash_calculation_accelaration/XGB_experience/../data/generate_data.py", line 428, in __getitem__
    target_data = Generate_data_from_csv(self.csv_train[self.materials[idx]],
IndexError: tuple index out of range
